version: '2.4'
#### Services ####
services:
  #### Data-Collector ####
  datacollector:
    build:
      context: ./src/data-collector
    image: data-collector_edge:0.0.2
    restart: always
    networks:
      - proxy-redirect
      - internal-network
    depends_on: 
      - influxdb
    volumes:
      - './publish/:/publish/'
      - './cfg-data/:/cfg-data/'
    mem_limit: 100mb

  #### InfluxDB ####
  influxdb:
    build:
      context: ./src/influxdb
    image: influxdb_edge:0.0.1
    restart: always
    networks:
      - internal-network
    volumes:
      - data:/var/lib/influxdb
    mem_limit: 250mb

  #### Grafana ####
  grafana:
    build:
      context: ./src/grafana
    image: grafana_edge:0.0.1
    restart: always
    networks:
      - internal-network
    volumes: 
      - dashboard-storage:/var/lib/grafana
    ports:
      - "33000:3000"
    mem_limit: 100mb


#### Network ####
networks:
  proxy-redirect:
    external: true
    name: proxy-redirect
  internal-network:
    name: internal-network

volumes:
  data:
  dashboard-storage:
    name: dashboard-storage
